// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXTpv_F5_XawLba26t4MRM3pdN56i9wA',
    appId: '1:2849440354:web:538281ccd9d3ae6f96873b',
    messagingSenderId: '2849440354',
    projectId: 'money-rise-81cd5',
    authDomain: 'money-rise-81cd5.firebaseapp.com',
    storageBucket: 'money-rise-81cd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDhndVJApnxX0EVmkIon8BjN-JZxPAM4c',
    appId: '1:2849440354:android:10e8dc3c6ce8119096873b',
    messagingSenderId: '2849440354',
    projectId: 'money-rise-81cd5',
    storageBucket: 'money-rise-81cd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-t99SdzW4pyJi_8m5NBFOUpqUeLeQHc',
    appId: '1:2849440354:ios:2335d3853a843eaa96873b',
    messagingSenderId: '2849440354',
    projectId: 'money-rise-81cd5',
    storageBucket: 'money-rise-81cd5.appspot.com',
    iosClientId: '2849440354-o7s5lvoj2eceqts8oe5h48h57ljdb1jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyRise',
  );
}
